version: '3.8'

services:

    wordpress:
        container_name: ${name}
        build: .
        image: wordpress-xdebug:latest
        # restart: on-failure
        ports:
            - 80:80
        environment:
            WORDPRESS_DB_HOST: ${name}_mysql
            WORDPRESS_DB_USER: ${db_user}
            WORDPRESS_DB_PASSWORD: ${db_pass}
            WORDPRESS_DB_NAME: ${db_name}
            XDEBUG_CONFIG: client_host=${xdebug_client_host}
        networks: 
            - wp_site
        volumes:
            - ./wp:/var/www/html
            - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    
    mysql:
        image: mysql:5.7
        container_name: ${name}_mysql
        # restart: unless-stopped
        volumes:
            - ../mysql:/var/lib/mysql/
        environment:
            MYSQL_DATABASE: ${db_name}
            MYSQL_USER: ${db_user}
            MYSQL_PASSWORD: ${db_pass}
            MYSQL_ROOT_PASSWORD: root
        networks:
            - wp_site

    phpmyadmin:
        container_name: ${name}_phpmyadmin
        image: phpmyadmin/phpmyadmin
        depends_on: 
            - mysql
        # restart: unless-stopped
        ports:
            - 8181:80
        environment:
            PMA_HOST: mysql
        networks:
            - wp_site

networks:
    wp_site:
        name: ${name}
