services:

    wordpress:
        container_name: ${name}
        build: .
        image: wordpress-xdebug:6.5.3
        # restart: on-failure
        ports:
            - 80:80
        environment:
            WORDPRESS_DB_HOST: ${name}_mysql
            WORDPRESS_DB_USER: ${db_user}
            WORDPRESS_DB_PASSWORD: ${db_pass}
            WORDPRESS_DB_NAME: ${db_name}
            WORDPRESS_DEBUG: true
            XDEBUG_CONFIG: client_host=${xdebug_client_host}
            XDEBUG_MODE: ${xdebug_mode}
            WP_TESTS_DIR: /var/www/vendor/wp-phpunit/wp-phpunit
            WP_TESTS_PHPUNIT_POLYFILLS_PATH: /var/www/vendor/yoast/phpunit-polyfills
            WP_PHPUNIT__TESTS_CONFIG: /var/www/wp-tests-config.php
        networks: 
            - wp_site
        volumes:
            - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./php.ini:/usr/local/etc/php/conf.d/custom-php.ini
            - ./wp:/var/www/html
            - ./vendor:/var/www/vendor
            - ./wp-tests-config.php:/var/www/wp-tests-config.php
            - ./composer.json:/var/www/composer.json
            - ./composer.lock:/var/www/composer.lock
    
    mysql:
        image: mysql:8
        container_name: ${name}_mysql
        # restart: unless-stopped
        volumes:
            - ../mysql:/var/lib/mysql/
            - ./initdb:/docker-entrypoint-initdb.d
        environment:
            MYSQL_DATABASE: ${db_name}
            MYSQL_USER: ${db_user}
            MYSQL_PASSWORD: ${db_pass}
            MYSQL_ROOT_PASSWORD: root
        networks:
            - wp_site

    phpmyadmin:
        container_name: ${name}_phpmyadmin
        image: phpmyadmin/phpmyadmin
        depends_on: 
            - mysql
        # restart: unless-stopped
        ports:
            - 8181:80
        environment:
            PMA_HOST: mysql
        networks:
            - wp_site

networks:
    wp_site:
        name: ${name}
